name: Content Generator Cron

on:
  schedule:
    - cron: '0 6 */2 * *'   # every 2 days at 6 AM UTC (~11:30 AM IST)
  workflow_dispatch:

jobs:
  generate-and-send:
    runs-on: ubuntu-latest

    steps:
      - name: Call API
        id: api
        run: |
          RESPONSE=$(curl -s https://content-pilot-j31k.onrender.com/getAutomatedContent)
          echo "response<<EOF" >> $GITHUB_OUTPUT
          echo "$RESPONSE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

#      - name: Send to Telegram
#        run: |
#          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
#          -d chat_id=${{ secrets.CHAT_ID }} \
#          -d text="${{ steps.api.outputs.response }}"